Velog
WE-SOPT-29th-Web-Part/Jiyoung-Hyun pull request #1
Opened 2021-10-07 08:05 UTC by shji023

## 📌 내용

### 기본과제
- 시맨틱태그로 작성하기
- flex활용해서 클론코딩

### 심화과제
- 일단 보류.. 나중에 꼭 할겁니다 ㅎㅎ

<br />

## 📌 PR Point

- ~부분 이렇게 구현했는데, 잘 한 것인지 모르겠습니다. 봐주시면 감사하겠습니다.

<br />

## 📌 스크린샷 
<!-- 구현 화면을 꼭 스크린샷 또는 gif로 보여주세요.  --
![velog](https://user-images.githubusercontent.com/60960130/136344716-942c7a80-167b-4600-8b72-9a9898d2a889.png)

2021-10-10 11:15 UTC, huiseon37 commented on velog/index.html
> +    <div>
저는 로고를 그냥 h2태그로 했는데 다음 과제 제출에는 img로 바꿔서 해야겠어요...! 생각지도 못했네요..반성...

2021-10-10 11:20 UTC, huiseon37 commented on velog/index.html
> +          <span><span>by</span> jiyoung</p>
요기 깜찍한 오타가 난거같아요~!

2021-10-10 11:22 UTC, huiseon37 commented on velog/index.html
> +    </article>
acticle 내부에 section으로 구분을 하셨네요..! 전 div만 썼는데 다음엔 section을 사용해 봐야 겠어요..!!

2021-10-10 11:24 UTC, huiseon37 commented on velog/style.css
> +}
select 박스로 구현하셔서 css를 어떻게 했을지 궁금했는데 그냥 div 구현하듯이 구현하면 되는거군요..! 혹시 이런 식으로 dropdown 됐을때 박스도 구현이 가능한가요?? 제가 잘 모르는 부분이라 궁금해서 여쭤봅니다~!

2021-10-10 11:25 UTC, huiseon37 commented on velog/style.css
> +}
오옷.. css 식별자를 잘 활용 하셨네요.. 저는 냅다 class이름 다 다르게 썼는데.. class name을 마구마구 짓지 않아도 되는거군요..!

2021-10-10 11:26 UTC, huiseon37 reviewed
wow 완벽해서 정말 토 달게 없었슴다... 심지어 제 코드랑 비교하면서 많이 배우고 가요!! 역시 지영언니 짱.. 갓지영

2021-10-12 10:43 UTC, shji023 commented on velog/index.html
> +    <div>
엇 이거는 그냥 벨록그처럼 보일려고 img로 넣은것ㅋㅋㅋㅋㅋ 제목이니까 제목태그로 해도될껄!!!

2021-10-12 10:44 UTC, shji023 commented on velog/style.css
> +}
태그를 일단 select로 사용하긴 햇는데 그안에 css는 적용을 안해서.. dropdown할라면 세미나때처럼 div로 바꿔야될꺼같아 .. !

2021-10-12 10:45 UTC, shji023 commented on velog/style.css
> +}
classname잘 활용하는 것도 좋습니다~~!~

2021-10-12 13:22 UTC, small-j requested changes
전체적으로 중복되는 css적용 없이 너무 잘 정리 되어 있다.. 이런게 바로 노련함인가 👍

2021-10-12 13:22 UTC, small-j commented on velog/style.css
> +}
우왓 저도 다 다르게 썼는데 selector 너무 잘 사용하셨네요 굳굳 👍

2021-10-12 13:22 UTC, small-j commented on velog/style.css
> +}
내가 코드리뷰 살짝 배워와서 드디어 리뷰를 할 수 있게 되었어ㅎㅎ
파일의 마지막 줄은 개행을 해주어야 한다고 해! 그래서 이렇게 빨간 동그라미가 생긴다고 하네 
eslint나 prettier 사용하면 자동으로 파일 마지막에 추가되도록 설정할 수 있다니까 우리 같이 하자!(나도 안되어 있다는 비밀..)

2021-11-04 07:05 UTC, merged