Feact: 할일 추가/제거 구현
WE-SOPT-29th-Web-Part/Jiyoung-Hyun pull request #3
Opened 2021-11-11 06:04 UTC by shji023

## 📌 내용
todo-list-react

### 기본과제
- 할일 추가/제거
- 오늘만보기 내일만보기 (추가 예정)
- 스타일 입히기 (추가 예정)
<br />

## 📌 PR Point

- ~부분 이렇게 구현했는데, 잘 한 것인지 모르겠습니다. 봐주시면 감사하겠습니다.

<br />

## 📌 스크린샷

2021-11-25 18:09 UTC, small-j requested changes
바쁨이 느껴지는 코드네요ㅋㅋㅋㅋㅋ 그리고 사실 저도 이 todo를 react로 변환하는걸 하지 않아서 적절한 코드리뷰였는지 모르겠지만.. 혹시 잘못한게 있다면 제게 가르침을 주시면 감사드리겠습니다.

2021-11-25 18:09 UTC, small-j commented on todo-list-react/src/App.js
> +        </SButton>
언니 많이 바빴구나..ㅋㅋㅋㅋㅋㅋ 이거 SButton 하나의 컴포넌트로 묶어서 map으로 돌려서 데이터 넘겨줘도 될것 같아!

2021-11-25 18:09 UTC, small-j commented on todo-list-react/src/App.js
> +        </STomorrow>
이것도 같은 형태이니 Today, Tomorrow를 같은 컴포넌트로 사용하면 좋지 않을까? 변경되는 부분은 인자로 전달하구 혹시 다른 이유로 나눠놓은 것이라면 제게 가르침을 주세요!

2021-11-25 18:09 UTC, small-j commented on todo-list-react/src/App.js
> +  visibility: ${(props) => (props.isToday ? "visible" : "hidden")};
난 이거 클디하면서 첨 써봤는데 빠르다 빨라 얼리어답터야 👍

2021-11-25 18:09 UTC, small-j commented on todo-list-react/src/App.js
> +  const [state, setState] = useState(2);
state 변수 이름을 좀 더 직관적으로 주면 좋을 것 같아욥 어떤 역할을 하는 state인지? todoSwitch, todoToggle,....

2021-11-25 18:09 UTC, small-j commented on todo-list-react/src/components/Tomorrow.jsx
> +  const onCreate = () => {
오 함수 이름 통일감 있게 잘 줬다

2021-11-27 08:40 UTC, SeojinSeojin commented on todo-list-react/src/App.js
> +  visibility: ${(props) => (props.isToday ? "visible" : "hidden")};
바로 구조분해할당도 가능하당!
```js
`
  width: ${({isToday}) => (isToday ? "100%" : "0")};
`
```

2021-11-27 12:45 UTC, shji023 commented on todo-list-react/src/App.js
> +        </SButton>
ㅋㅋㅋㅋ 마져 ..ㅋㅋㅋ 그냥 갈겨버렸네,,,

2021-11-27 12:45 UTC, shji023 commented on todo-list-react/src/App.js
> +  visibility: ${(props) => (props.isToday ? "visible" : "hidden")};
오옹 서진 고마왕

2021-11-27 12:46 UTC, shji023 commented on todo-list-react/src/App.js
> +  const [state, setState] = useState(2);
그러네요 todoSwitch좋은생각!!

2021-11-27 12:49 UTC, shji023 commented on todo-list-react/src/App.js
> +        </STomorrow>
아 오 그러네 ? 플레이스홀더 빼고 같은 다 똑같네 한번 하나로 합쳐봐야겟다 땡큐~!!

2021-11-29 11:21 UTC, merged